### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by EHLOVader** [mykebates/wp-rocketeer#1]
Knowing this is an unfinished project I was curious if there was any recommendation for how to handle plugins.

I had been using Yeoman in my local dev also but through https://github.com/lkwdwrd/generator-vvv which keeps theme and plugins separate.

I would like to have the same sort of configuration for deploying if possible. Any suggestions?

**Comment by mykebates** [comment]
Hey there.  lol, yes, your are correct - a very much unfinished project :)  Kind of fell out of doing so much WP work and never got the chance to spruce this up.  I imagine there are plenty of other techniques out there by now.

So, as far as running that generator tool, you can certainly user rocketeer's hook system to fire a task that runs the commands needed.  I poked around that generator's documentation but would take a bit to figure out everything needed.

I am not sure what your hosting situation looks like, but Envoyer from the Laravel side of the PHP world recently released and it has some pretty slick features for deployment.  Might be worth looking into(note: it is not just a Laravel thing).

Anyways, good luck with this.  Rock solid WP deployments is something that is really needed for the dev community so I feel your pain.
